### ISSUE TITLE
Append user dependencies to default list

### ISSUE THREAD

**Issue by fcastilloec** [unindented/electron-installer-debian#108]
As we were talking in #105, I'm creating this issue just so we can keep track of what we need to do regarding duplicate dependencies and the new behavior.

## TODO
- [ ] append user dependencies to the default ones
- [ ] use Sets to prevent duplicate dependencies
- [ ] update README showing default dependencies and the new append behavior
